2024-12-21 02:51:28,918 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 02:58:56,232 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:02:29,492 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:02:33,209 ERROR: Exception on /login [GET] [in /home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/routes.py", line 72, in login
    return render_template('login.html', title='Sign In', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lucas/microblog/app/templates/login.html", line 103, in top-level template code
    value="{{ form.email.data if form.email.data else '' }}">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.forms.LoginForm object' has no attribute 'email'
2024-12-21 03:07:12,923 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:07:24,248 ERROR: Exception on /login [POST] [in /home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/routes.py", line 63, in login
    user = User.query.filter_by(username=form.username.data).first()
                                         ^^^^^^^^^^^^^
AttributeError: 'LoginForm' object has no attribute 'username'
2024-12-21 03:08:35,355 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:11:00,839 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:11:00,839 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:11:00,839 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:11:01,050 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:11:28,260 ERROR: Exception on /register [GET] [in /home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/routes.py", line 107, in register
    return render_template('register.html', title='Register', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lucas/microblog/app/templates/register.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/lucas/microblog/app/templates/base.html", line 132, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/templates/register.html", line 8, in block 'content'
    <!--            {{ form.username.label }}<br>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.forms.RegistrationForm object' has no attribute 'username'
2024-12-21 03:11:53,458 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:12:02,375 ERROR: Exception on /register [GET] [in /home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/routes.py", line 107, in register
    return render_template('register.html', title='Register', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/lucas/microblog/app/templates/register.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/lucas/microblog/app/templates/base.html", line 132, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/app/templates/register.html", line 8, in block 'content'
    <!--            {{ form.username.label }}<br>
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/microblog/venv/lib/python3.12/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'app.forms.RegistrationForm object' has no attribute 'username'
2024-12-21 03:18:41,972 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:19:05,294 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:20:13,604 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:20:13,604 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:20:13,609 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
2024-12-21 03:20:13,611 INFO: Microblog startup [in /home/lucas/microblog/app/__init__.py:32]
